hmcts/lau-frontend

charts/lau-frontend/values.preview.template.yaml, charts/lau-frontend/values.yaml, config/default.yaml, config/development.yaml, docker-compose.yml, src/main/assets/scss/main.scss, src/main/controllers/CaseActivity.controller.ts, src/main/controllers/CaseSearches.controller.ts, src/main/controllers/Logon.controller.ts, src/main/models/appRequest.ts, src/main/models/case/CaseActivityAudit.ts, src/main/models/case/CaseSearchAudit.ts, src/main/models/idam/LogonAudit.ts, src/main/modules/session/index.ts, src/main/service/AuthService.ts, src/main/service/BaseService.ts, src/main/service/CaseService.ts, src/main/service/LogonService.ts, src/main/views/case-activity/template.njk, src/main/views/case-searches/template.njk, src/main/views/logons/template.njk, src/test/data/caseActivityLogs.json, src/test/data/caseSearchLogs.json, src/test/data/logonLogs.json, src/test/unit/controllers/case-activity.test.ts, src/test/unit/controllers/case-searches.test.ts, src/test/unit/routes/caseActivity.test.ts, src/test/unit/service/AuthService.test.ts, src/test/unit/service/CaseService.test.ts, src/test/unit/service/LogonService.test.ts
https://tools.hmcts.net/jira/browse/LAU-207
```
[ ] Yes
[x] No
```
=> LAU-27: Results page changes

src/main/controllers/Logon.controller.ts, src/main/models/idam/LogonLogs.ts, src/main/views/logons/template.njk
https://tools.hmcts.net/jira/browse/LAU-203
Add service column to logons data
```
[ ] Yes
[x] No
```
=> LAU-203 Add service column to logons data

package.json, src/main/controllers/Logon.controller.ts, src/main/models/appRequest.ts, src/main/modules/oidc/index.ts, src/main/modules/session/index.ts, src/main/service/AuthService.ts, src/main/service/BaseService.ts, src/main/service/CaseService.ts, src/main/service/LogonService.ts, src/test/unit/service/AuthService.test.ts, src/test/unit/service/CaseService.test.ts
https://tools.hmcts.net/jira/browse/LAU-224
Increase session timeout. Implement IdAM token refresh.
```
[ ] Yes
[x] No
```
=> LAU-224 Increase session timeout. Implement IdAM token refresh.

package.json, src/main/models/appRequest.ts, src/main/modules/oidc/index.ts, src/main/modules/session/index.ts, src/main/service/AuthService.ts, src/main/service/BaseService.ts, src/main/service/CaseService.ts, src/main/service/LogonService.ts, src/test/unit/service/AuthService.test.ts, src/test/unit/service/CaseService.test.ts
=> Revert "LAU-224 Increase session timeout. Implement IdAM token refresh."

config/development.yaml, src/main/util/CsvHandler.ts, src/main/views/case-activity/template.njk, src/main/views/case-searches/template.njk, src/main/views/logons/template.njk, src/test/unit/utils/csvHandler.test.ts
https://tools.hmcts.net/jira/browse/LAU-239
Add (UTC) to Timestamp headers
```
[ ] Yes
[x] No
```
=> LAU-239 Add (UTC) to Timestamp headers

src/main/assets/scss/main.scss, src/main/controllers/CaseActivity.controller.ts, src/main/controllers/CaseSearches.controller.ts, src/main/controllers/Logon.controller.ts, src/main/views/search/case-template.njk, src/main/views/search/logon-template.njk, src/test/unit/controllers/case-activity.test.ts, src/test/unit/controllers/case-searches.test.ts, src/test/unit/controllers/logon.test.ts
https://tools.hmcts.net/jira/browse/LAU-263
Fix data table formatting to prevent data overflowing outside table.
```
[ ] Yes
[x] No
```
=> LAU-263 Fix data table formatting

.dockerignore, .gitignore, Dockerfile, charts/lau-frontend/Chart.yaml, charts/lau-frontend/values.yaml, config/custom-environment-variables.yaml, config/default.yaml, config/development.yaml, config/test.yaml, createVersionFile.js, docker-compose.yml, package.json, src/main/app.ts, src/main/modules/health/index.ts, src/main/modules/oidc/index.ts, src/main/modules/properties-volume/index.ts, src/main/modules/session/index.ts, src/main/service/AuthService.ts, src/main/service/BaseService.ts, src/main/service/CaseService.ts, src/main/service/LogonService.ts, src/test/service-stubs/lau-case-backend.js, src/test/service-stubs/lau-idam-backend.js, src/test/unit/service/AuthService.test.ts, src/test/unit/service/CaseService.test.ts, src/test/unit/service/LogonService.test.ts
https://tools.hmcts.net/jira/browse/LAU-281
- Updated Redis healthcheck to use timeout to prevent 500 errors on the healthcheck
- Add LAU backend and IDAM services to healthcheck
- Add version file to show commit and version details on healthcheck endpoint.
- Some refactoring of variable names.
```
[ ] Yes
[x] No
```
=> LAU-281 Update Healthcheck and include version file

src/main/service/CaseService.ts, src/main/service/LogonService.ts
https://tools.hmcts.net/jira/browse/LAU-286
Prevent changes to search params for CSV do not persist in session.
```
[ ] Yes
[x] No
```
=> LAU-286 Prevent changes to search params for CSV do not persist in session

Dockerfile, createVersionFile.js, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-289
Replace exec-sync with package to fix fortify issues
```
[ ] Yes
[x] No
```
=> LAU-289 Replace exec-sync with package

package.json, src/main/views/common/webpack/css-template.njk, src/main/views/common/webpack/css.njk
Revert flatpickr preload
```
[ ] Yes
[x] No
```
=> Revert flatpickr preload

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-351
Fiv vulnerability in FE.
```
[ ] Yes
[x] No
```
=> LAU-351: Fix vulnerability.

package.json, src/test/end-to-end/codecept.conf.js, src/test/end-to-end/lauApi/lauHelper.js, src/test/end-to-end/pages/lauHomePage/caseAuditSearchWithoutSearchData.js, src/test/end-to-end/pages/lauHomePage/caseSearch.js, src/test/end-to-end/pages/lauHomePage/logonAuditSearch.js, src/test/end-to-end/pages/lauHomePage/logonAuditSearchWithoutSearchData.js, src/test/end-to-end/pages/steps.js, src/test/end-to-end/paths/homePageLau.js, src/test/end-to-end/paths/logonPage.js
=> LAU-339/ Automate CaseActivity tab

package.json, src/main/assets/js/cookie.ts, src/main/assets/scss/main.scss, src/main/views/common/template.njk, src/main/views/cookies/content.ts, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-368
Update cookie manager. Minor fixes.
```
[ ] Yes
[x] No
```
=> LAU-368 Cookie manager update

package.json, src/main/routes/home.ts, src/main/views/common/template.njk, src/main/views/common/webpack/css-template.njk, src/main/views/common/webpack/css.njk, src/test/end-to-end/paths/logonPage.js
https://tools.hmcts.net/jira/browse/LAU-346
Add feature toggle to flatpickr preload.
```
[ ] Yes
[x] No
```
=> LAU-346 Add feature toggle for Flatpickr preload

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-371
Fix dependency check issue with moment.
```
[ ] Yes
[x] No
```
=> LAU-371: Fix dependency check issue.

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-372
Update to async module version.
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
=> LAU-372: Dependency fixes

audit.json, charts/lau-frontend/Chart.yaml, charts/lau-frontend/values.yaml, package.json, src/test/end-to-end/paths/homePageLau.js
https://tools.hmcts.net/jira/browse/LAU-420
This change is to fix Security Scan
```
[ ] Yes
[x] No
```
=> LAU-420 Security Scan fix

Dockerfile, package.json
https://tools.hmcts.net/jira/browse/LAU-370
Upgrade NodeJS to Version 16 (latest LTS version)
```
[ ] Yes
[x] No
```
=> LAU-370 Upgrade NodeJS to Version 16

charts/lau-frontend/Chart.yaml, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-460
Upgrade NodeJS chart version to 2.4.5
```
[ ] Yes
[x] No
```
=> Upgrade chart nodejs version

package.json, src/main/views/common/template.njk
https://tools.hmcts.net/jira/browse/LAU-403
Add aria state property to cookie accept/decline buttons
```
[ ] Yes
[x] No
```
=> LAU-403 Add aria state property

audit.json
https://tools.hmcts.net/jira/browse/LAU-482
This change is to fix Security scan.
```
[ ] Yes
[x] No
```
=> LAU-482 Security scan fix

package.json, src/main/modules/health/index.ts, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-475
- Update nodejs-healthcheck module
- Increase Redis ping timeout from 1.2s to 5s
```
[ ] Yes
[x] No
```
=> LAU-475 Update healthcheck module and increase redis ping timeout

package.json, src/main/assets/scss/main.scss, webpack/govukFrontend.js, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-533
GOV UK Frontend Framework 4.0 Upgrade
```
[ ] Yes
[x] No
```
=> LAU-533 GOV UK Frontend Framework 4.0 Upgrade

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-536
Dependency check fix for missmatch lib.
```
[ ] Yes
[x] No
```
=> LAU-536: Dependency fix.

bin/githooks/pre-commit, createVersionFile.js, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-534
Fix version data for healthcheck
```
[ ] Yes
[x] No
```
=> LAU-534 Fix version data for healthcheck

Dockerfile, package.json, src/main/assets/js/home.ts, src/main/assets/scss/main.scss, src/main/modules/health/index.ts, src/main/views/case-activity/template.njk, src/main/views/case-deletions/template.njk, src/main/views/case-searches/template.njk, src/main/views/common/template.njk, src/main/views/common/webpack/css-template.njk, src/main/views/common/webpack/css.njk, src/main/views/common/webpack/js-template.njk, src/main/views/common/webpack/js.njk, src/main/views/logons/template.njk, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-288
Reorganise resource loading
```
[ ] Yes
[x] No
```
=> LAU-288 Reorganise resource loading

Dockerfile
https://tools.hmcts.net/jira/browse/LAU-551
Removing lines as Fortify complaining about Misconfiguration dependency confusion
```
[ ] Yes
[x] No
```
=> LAU-551 removing user to build image

.github/PULL_REQUEST_TEMPLATE.md, Jenkinsfile_CNP, package.json, src/main/models/Logs.ts, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-549
Cleanup helm release on success
```
[ ] Yes
[x] No
```
=> LAU-549 Cleanup helm release on success

charts/lau-frontend/Chart.yaml, charts/lau-frontend/values.preview.template.yaml
Remove lau pr url from preview template
```
[ ] Yes
[x] No
```
=> Remove lau pr url from preview template

.dependabot/config.yml
https://tools.hmcts.net/jira/browse/LAU-611
This change is to configure dependabot on particular day
```
[ ] Yes
[x] No
```
=> LAU-611 configuring dependabot on Particular Day

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-644
This change is to upgrade nunjucks to 3.2.4
```
[ ] Yes
[x] No
```
=> LAU-644 nunjucks upgrade

.gitignore, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/LAU-670
Upgrade Redis cache to v6
```
[ ] Yes
[x] No
```
=> LAU-670 Upgrade Redis cache to v6

infrastructure/main.tf
https://github.com/hmcts/cnp-module-redis/pull/33 is now merged
=> Back to master branch of the redis module

yarn.lock
Fix dependabot version update
Fix dependabot version update
```
[ ] Yes
[x] No
```
=> Fix dependabot version update

src/main/modules/oidc/index.ts
https://tools.hmcts.net/jira/browse/LAU-696
Remove session on logout
```
[ ] Yes
[x] No
```
=> Remove session on logout

src/main/views/common/webpack/css-template.njk, src/main/views/common/webpack/css.njk, yarn.lock
It looks like some of the CSS cannot be preloaded and causing stylesheet issues.
```
[ ] Yes
[x] No
```
=> Remove flatpickr preload

charts/lau-frontend/Chart.yaml, src/main/app.ts, src/main/modules/appinsights/index.ts, src/main/server.ts, src/main/views/common/webpack/css-template.njk, src/main/views/common/webpack/css.njk
https://tools.hmcts.net/jira/browse/LAU-694
=> LAU-694: AppInsights logging fix

src/main/app.ts
https://tools.hmcts.net/jira/browse/LAU-694
=> LAU-694: Temporarily disable compression

src/test/java/build.gradle, src/test/java/gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/LAU-711
Bump gradle version
```
[ ] Yes
[x] No
```
=> Lau 711 fix fortify scan failure

package.json, src/main/app.ts, yarn.lock
https://tools.hmcts.net/jira/projects/LAU/issues/LAU-707
Disable acceptRanges on static files. Compression and range requests do not work well on Azure Front Door.
```
[ ] Yes
[x] No
```
=> LAU-707 disable range requests that do not work well with compression

package.json
Disabling functional tests, so that our fix for timeouts could be deployed and we can test whether it fixes the issue
```
[ ] Yes
[x] No
```
=> disable functional tests

src/main/app.ts
Disable cache as it makes frontend misbehave
```
[ ] Yes
[x] No
```
=> disable cache due to weird browsing results

src/main/app.ts
Reverting back to default range request handling 
```
[ ] Yes
[x] No
```
=> revert back to version that has issue with azure front door

package.json, src/main/app.ts
https://tools.hmcts.net/jira/browse/LAU-707
Disable Accept-Ranges header
```
[ ] Yes
[x] No
```
=> Fix stylesheet issue

package.json
Unable functional tests
Unable functional tests
```
[ ] Yes
[x] No
```
=> Unable functional tests

src/test/end-to-end/common/Constants.js, src/test/end-to-end/pages/lauHomePage/deletedUsersSearch.js, src/test/end-to-end/pages/lauHomePage/deletedUsersSearchWithoutSearchData.js, src/test/end-to-end/pages/steps.js, src/test/end-to-end/paths/deletedUserPage.js
https://tools.hmcts.net/jira/browse/LAU-729
This change is to add functional tests for Deleted users
```
[ ] Yes
[x] No
```
=> Frontend functional test

.github/renovate.json
Configure renovate to group PRs, and run between 1500 and 1900.
```
[ ] Yes
[x] No
```
=> update renovate to group PRs

audit.json
remove some url which not needed
```
[ ] Yes
[x] No
```
=> Revert audit.json

config/default.yaml, src/main/assets/js/session-timeout.ts, src/main/assets/scss/main.scss, src/main/assets/scss/timeout-modal.scss, src/main/index.ts, src/main/modules/session/index.ts, src/main/routes/active.ts, src/main/routes/home.ts, src/main/views/common/template.njk, src/main/views/common/timeout-dialog.njk, src/test/unit/controllers/deleted-users-search.tests.ts, src/test/unit/controllers/logon-search.test.ts, src/test/unit/controllers/logon.test.ts, src/test/unit/routes/active.test.ts, src/test/unit/routes/deletedUsers.test.ts, src/test/unit/routes/logonAudit.test.ts
LAU-808
Added timer to logout after inactivity and popup to show before logging out.
```
[ ] Yes
[x] No
```
=> LAU-808 logout after inactivity

package.json, yarn.lock
=> bump puppeteer

charts/lau-frontend/Chart.yaml, charts/lau-frontend/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/LAU-853
Remove custom redis from preview
=> LAU-853 remove custom redis for preview

config/default.yaml, src/main/modules/appinsights/index.ts
[LAU-847](https://tools.hmcts.net/jira/browse/LAU-847)
Remove health endpoints requests logging
=> LAU-847 remove health requests logging

src/main/modules/helmet/index.ts, src/main/modules/oidc/index.ts, webpack/govukFrontend.js
[LAU-854](https://tools.hmcts.net/jira/browse/LAU-854)
Fixed the errors that were logged in browsers console window
=> LAU-854 fix console logged errors

charts/lau-frontend/Chart.yaml, charts/lau-frontend/values.yaml
Disable spot instances, they do not work.
=> disable spot instances

Jenkinsfile_CNP, src/main/views/case-audit/template.njk, src/test/end-to-end/codecept.conf.js, src/test/end-to-end/common/Constants.js, src/test/end-to-end/lauApi/lauHelper.js, src/test/end-to-end/pages/lauHomePage/caseAuditSearch.js, src/test/end-to-end/pages/lauHomePage/caseAuditSearchWithoutSearchData.js, src/test/end-to-end/pages/lauHomePage/caseSearch.js, src/test/end-to-end/pages/lauHomePage/deletedUsersSearch.js, src/test/end-to-end/pages/lauHomePage/logonAuditSearch.js, src/test/end-to-end/paths/deletedUserPage.js, src/test/end-to-end/paths/homePageLau.js, src/test/end-to-end/paths/logonPage.js
[LAU-890](https://tools.hmcts.net/jira/browse/LAU-890)
Update functional tests to reflect new design
=> LAU-890 fix functional tests

Jenkinsfile_CNP
=> LAU set PR env on PR only

package.json
Temporarily disable functional tests to pass master pipeline
=> fix functional tests

package.json
=> restore functional tests

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/LAU-841
Run security scan once a month on 15th if it is not weekend.
=> LAU-841 run security scan once a month

infrastructure/state.tf, package.json, src/main/app.ts, src/main/modules/csrf/index.ts, src/main/views/case-audit/template.njk, src/main/views/case-deletions/template.njk, src/main/views/logons/template.njk, src/main/views/user-deletions/template.njk, src/test/helpers/csrf.ts, src/test/helpers/post.ts, src/test/helpers/roles.ts, src/test/unit/routes/active.test.ts, src/test/unit/routes/home.test.ts, src/test/unit/routes/search.test.ts, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-811
added csrf-sync lib
created a new module to setup csrf-sync lib
added csrf token to all forms that require protecting
```
[ ] Yes
[X] No
```
=> added csrf tokens to forms and validation endpoints

src/main/views/case-audit/template.njk, src/main/views/case-deletions/template.njk, src/main/views/logons/template.njk, src/main/views/user-deletions/template.njk
https://tools.hmcts.net/jira/browse/LAU-896
Add page titles
```
[ ] Yes
[x] No
```
=> LAU-896 Add page titles

src/main/views/case-audit/template.njk, src/main/views/case-deletions/template.njk, src/main/views/common/macros/lauDateTimeInput.njk, src/main/views/logons/template.njk, src/main/views/user-deletions/template.njk
https://tools.hmcts.net/jira/browse/LAU-897
Add date hints
```
[ ] Yes
[x] No
```
=> LAU-897 Add Date hints.

charts/lau-frontend/Chart.yaml, package.json
Upgrade chart and package version
```
[ ] Yes
[x] No
```
=> Upgrading charts version

charts/lau-frontend/values.aat.template.yaml
=> Change redirect url for staging and aat

Jenkinsfile_CNP, charts/lau-frontend/values.aat.template.yaml
=> Run FTs against staging env

package.json, yarn.lock
This reverts commit 630c8b5a44a1f34b1545d6cad3c71fc40719da23.
```
[ ] Yes
[ ] No
```
=> Revert "Update dependency sass-loader to v16 (#714)"

src/main/views/logons/template.njk, src/main/views/user-deletions/template.njk
Email layout
```
[ ] Yes
[x] No
```
=> Fix email layout

charts/lau-frontend/Chart.yaml, charts/lau-frontend/values.aat.template.yaml, charts/lau-frontend/values.preview.template.yaml, charts/lau-frontend/values.yaml
=> Fix is_dev in the charts

src/main/service/CaseTypeJurisdictionAutoSuggest.ts
logger to output what file autosuggest is using
```
[ ] Yes
[ ] No
```
=> added logger to output autosuggest file being used

src/test/unit/controllers/deleted-users.test.ts
https://tools.hmcts.net/jira/browse/LAU-757
update unit tests to check res.redirect is returning the actual value
```
[ ] Yes
[ ] No
```
=> update unit test to use jest mock and validate the outcome

package.json, yarn.lock
fix vulnerability
```
[ ] Yes
[x] No
```
=> Fix-vulnerability

src/main/routes/home.ts, src/main/views/case-deletions/template.njk
https://tools.hmcts.net/jira/browse/LAU-962
Case deletion tab selection and type ahead fields
```
[ ] Yes
[x] No
```
=> LAU-962  cft-service-logs role page

src/main/service/FeatureToggleService.ts, src/test/end-to-end/paths/challengedSpecificAccessPage.js, src/test/unit/components/LaunchDarklyClient.test.ts, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-959
Enabling challenged and specific tab on dev mode
```
[ ] Yes
[x] No
```
=> LAU-959 enabling challended and specific tab on development

package.json, yarn.lock
Cookie upgrade
```
[ ] Yes
[x] No
```
=> cookie upgrade

src/main/views/case-challenged-access/template.njk, src/main/views/common/navigation.njk, src/test/end-to-end/paths/challengedSpecificAccessPage.js
=> Update challeged and specific access title

src/main/controllers/CaseChallengedAccess.controller.ts
https://tools.hmcts.net/jira/browse/LAU-988
```
[ ] Yes
[x] No
```
=> Make reason field Optional

src/main/controllers/CaseChallengedAccess.controller.ts, src/main/views/case-challenged-access/template.njk, src/main/views/common/access-request-results-header.njk, webpack/app.js
https://tools.hmcts.net/jira/browse/LAU-982
Add Access request user guide
```
[ ] Yes
[x] No
```
=> LAU-982 Add Access request user guide

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/LAU-1006
Cross-spawn upgrade
```
[ ] Yes
[x] No
```
=> LAU-1006 cross-spawn upgrade

package.json, yarn.lock
nano library upgrade 
```
[ ] Yes
[x] No
```
=> nanoid fix

src/main/components/featureToggle/LaunchDarklyClient.ts
https://tools.hmcts.net/jira/browse/LAU-1096
Remove info message from launch darkly that unnecessary clutters our logs
=> LAU-1096 remove LD log message

src/main/app.ts, src/main/assets/scss/main.scss
Change at which stage static files are served to improve performance
```
[ ] Yes
[x] No
```
=> shuffle static files serve

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/CME-233
```
[ ] Yes
[ ] No
```
=> CME-233: terraform provider bump

charts/lau-frontend/Chart.yaml
Nodejs chart to OCI version
```
[ ] Yes
[x] No
```
=> Bump nodejs chart to oci

src/main/service/BaseService.ts, src/test/end-to-end/helpers/JSWait.js, src/test/end-to-end/helpers/accessibility/runner.js
https://tools.hmcts.net/jira/browse/LAU-1130
Do not pass _csrf token to java backends from lau-frontend
=> LAU-1130 do not pass _csrf token to java backends

src/test/java/build.gradle
lau-fortify-client upgrade
```
[ ] Yes
[x] No
```
=> lau-fortify-upgrade

package.json, yarn.lock
Upgrade Formidable library
```
[ ] Yes
[x] No
```
=> Upgrade formidable library

src/main/views/common/dynatrace/head.njk
https://tools.hmcts.net/jira/browse/LAU-1133
Adding Dynatrace script on production
```
[ ] Yes
[x] No
```
=> Lau-1133 adding dynatrace script for production

src/main/views/common/macros/paging.njk, src/test/end-to-end/paths/challengedSpecificAccessPage.js, src/test/end-to-end/paths/deletedUserPage.js, src/test/end-to-end/paths/homePageLau.js, src/test/end-to-end/paths/logonPage.js
https://tools.hmcts.net/jira/browse/LAU-1154
Update Next, Last and Previus labels
```
[ ] Yes
[x] No
```
=> Fix Pagination Links Lack Context

src/main/views/case-audit/template.njk, src/main/views/case-challenged-access/template.njk, src/main/views/case-deletions/template.njk, src/main/views/common/error/summary.njk, src/main/views/logons/template.njk, src/main/views/user-deletions/template.njk, src/test/end-to-end/pages/lauHomePage/caseChallengedAccessSearch.js
https://tools.hmcts.net/jira/browse/LAU-1148
```
[ ] Yes
[x] No
```
=> Update error message link to point to first available search field

package.json, yarn.lock
Fix brace-expansion vunerability
```
[ ] Yes
[x] No
```
=> Fix LAU brace-expansion vunerainility

src/main/views/common/result-header.njk
https://tools.hmcts.net/jira/browse/LAU-1190
Add warning
```
[ ] Yes
[x] No
```
=> LAU-1190 - Link Opens in New Tabs Without Warning

package.json, yarn-audit-known-issues, yarn.lock
Bump form-data library
```
[ ] Yes
[x] No
```
=> bump form-data

charts/lau-frontend/Chart.yaml, charts/lau-frontend/values.yaml
LAU-1176
Remove alias to instrumentation key so that connection string can be used
```
[ ] Yes
[x] No
```
=> LAU-1176 replace appinsights instrumentation key with connection string
